OPENAI_API_KEY = "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"
WEATHERAPI_KEY = "ca32a83869b94eafabe230429252107"
GEOCODE_KEY = "8da6dfee34884c5f8a0f746f674c249d"